version: '3.1'
services:
  postgresql-server:
    container_name: postgresql-server
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  wallet:
    container_name: wallet
    build: .
    environment:
      POSTGRESQL_URL: jdbc:postgresql://postgresql-server/wallet
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgresql-server